export const RESTAURANT = {
  name: 'Savoria',
  tagline: 'Artisanal Hearth & Dining Sanctuary',
  founded: 2012,
  address: '428 Heritage Boulevard, Colombo',
  phone: '+1 (555) 234-7890',
  reservationPhone: '+1 (555) 234-7899',
  email: 'concierge@savoria.com',
  hours: [
    { days: 'Monday – Thursday', lunch: '11:30 AM – 2:30 PM', dinner: '5:00 PM – 10:00 PM' },
    { days: 'Friday – Saturday', lunch: '11:30 AM – 3:00 PM', dinner: '5:00 PM – 11:30 PM' },
    { days: 'Sunday Brunch & Dinner', lunch: '10:30 AM – 3:30 PM', dinner: '5:00 PM – 9:30 PM' },
  ],
  delivery: {
    minimum: 25,
    fee: 4.5,
    freeOver: 75,
    time: '30 - 45 mins',
    zones: ['Downtown & Financial District', 'Old Quarter', 'West Marina', 'Highland Park', 'Oakridge Terrace'],
  }
};

export const CHEF = {
  name: 'Chef Silva',
  title: 'Executive Chef & Co-Founder',
  experience: '22 Years of Culinary Mastery',
  origin: 'Colombo & Lyon',
  image: 'https://images.unsplash.com/photo-1577219491135-ce391730fb2c?auto=format&fit=crop&w=800&q=80',
  bio: 'Trained under French culinary icons and rooted in hyper-seasonal organic agriculture, Chef Silva founded Savoria to celebrate the pure flavor of ingredients cultivated within hours of harvest.',
  quote: 'Every plate must honor the soil and the artisans who nurtured its harvest.',
  accolades: [
    'Best Chef Award (2021, 2024)',
    'Sustainable Cuisine Green Emblem (2023)',
    '3x National Culinary Gold Medallion',
    'Sommelier Choice Guild Selection'
  ],
  milestones: [
    { year: '2012', title: 'The Sanctuary Opens', desc: 'Inaugurated as an intimate 14-table tasting room focusing on wood-fired techniques.' },
    { year: '2018', title: '15-Acre Valley Bio-Farm', desc: 'Acquired our regenerative bio-farm supplying 100% pesticide-free produce daily.' },
    { year: '2024', title: 'Zero-Waste Kitchen', desc: 'Achieved complete closed-loop composting and carbon-neutral express delivery.' }
  ]
};

export const DISHES = [
  {
    id: 'dish-1',
    name: 'Pan-Seared Hokkaido Scallops',
    category: 'starters',
    price: 24,
    desc: 'Golden caramelized diver scallops atop saffron velouté, dehydrated Serrano crisps, and pea tendrils.',
    image: 'https://images.unsplash.com/photo-1532550907401-a500c9a57435?auto=format&fit=crop&w=700&q=80',
    rating: 4.9,
    reviews: 142,
    calories: 380,
    prepTime: '15 mins',
    tags: ["Chef's Choice", 'Gluten-Free'],
    macros: { protein: '28g', carbs: '9g', fats: '18g' },
    ingredients: ['Diver Scallops', 'Kashmiri Saffron', 'Shallot Reduction', 'Normandy Butter', 'Serrano Crisp'],
    allergens: ['Shellfish', 'Dairy'],
    isFeatured: true
  },
  {
    id: 'dish-2',
    name: 'Apulian Burrata & Roasted Figs',
    category: 'starters',
    price: 19,
    desc: 'Creamy burrata heart, honey-roasted mission figs, toasted pine nuts, and 25-year Modena balsamic.',
    image: 'https://images.unsplash.com/photo-1592417817098-8f3d6910985b?auto=format&fit=crop&w=700&q=80',
    rating: 4.8,
    reviews: 98,
    calories: 460,
    prepTime: '12 mins',
    tags: ['Vegetarian', 'Organic'],
    macros: { protein: '18g', carbs: '24g', fats: '32g' },
    ingredients: ['Apulian Burrata', 'Mission Figs', 'Toasted Pine Nuts', 'Wild Basil', 'Aged Balsamic'],
    allergens: ['Dairy', 'Tree Nuts'],
    isFeatured: false
  },
  {
    id: 'dish-3',
    name: 'Prime Angus Filet Mignon',
    category: 'mains',
    price: 48,
    desc: 'Center-cut 28-day aged beef filet over Robuchon butter potato purée, charred broccolini, and black truffle demi-glace.',
    image: 'https://images.unsplash.com/photo-1558030006-450675393462?auto=format&fit=crop&w=700&q=80',
    rating: 5.0,
    reviews: 230,
    calories: 680,
    prepTime: '25 mins',
    tags: ["Chef's Choice", 'Gluten-Free'],
    macros: { protein: '52g', carbs: '22g', fats: '38g' },
    ingredients: ['Aged Beef Filet', 'Yukon Potatoes', 'Winter Truffle', 'Charred Broccolini', 'Bone Reduction'],
    allergens: ['Dairy'],
    isFeatured: true
  },
  {
    id: 'dish-4',
    name: 'Wild Chilean Sea Bass en Papillote',
    category: 'mains',
    price: 44,
    desc: 'Oven-steamed in parchment with lemongrass, shaved fennel, shiitake mushrooms, and dashi citrus infusion.',
    image: 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?auto=format&fit=crop&w=700&q=80',
    rating: 4.9,
    reviews: 114,
    calories: 520,
    prepTime: '22 mins',
    tags: ['Gluten-Free', 'Organic'],
    macros: { protein: '42g', carbs: '12g', fats: '24g' },
    ingredients: ['Chilean Sea Bass', 'Lemongrass', 'Fennel Bulb', 'Shiitake Caps', 'Dashi Broth'],
    allergens: ['Fish'],
    isFeatured: true
  },
  {
    id: 'dish-5',
    name: 'Truffled Buffalo Ricotta Ravioli',
    category: 'pasta',
    price: 32,
    desc: 'Handmade semolina pasta pillows stuffed with buffalo ricotta, tossed in brown sage butter and shaved Norcia truffles.',
    image: 'https://images.unsplash.com/photo-1587740908075-9e245070dfaa?auto=format&fit=crop&w=700&q=80',
    rating: 4.9,
    reviews: 184,
    calories: 590,
    prepTime: '18 mins',
    tags: ['Vegetarian', "Chef's Choice"],
    macros: { protein: '22g', carbs: '64g', fats: '28g' },
    ingredients: ['Egg Semolina', 'Buffalo Ricotta', 'Norcia Black Truffle', 'Parmigiano-Reggiano', 'Sage Butter'],
    allergens: ['Gluten', 'Eggs', 'Dairy'],
    isFeatured: true
  },
  {
    id: 'dish-6',
    name: 'Wild Chanterelle Carnaroli Risotto',
    category: 'pasta',
    price: 29,
    desc: 'Aged Carnaroli rice slow-cooked with roasted mushrooms, saffron threads, mascarpone, and crispy trumpet chips.',
    image: 'https://images.unsplash.com/photo-1633964913295-ceb43826e7c9?auto=format&fit=crop&w=700&q=80',
    rating: 4.8,
    reviews: 89,
    calories: 540,
    prepTime: '20 mins',
    tags: ['Vegetarian', 'Gluten-Free', 'Organic'],
    macros: { protein: '14g', carbs: '68g', fats: '22g' },
    ingredients: ['Carnaroli Rice', 'Chanterelles', 'Saffron', 'Mascarpone', 'White Truffle Oil'],
    allergens: ['Dairy'],
    isFeatured: false
  },
  {
    id: 'dish-7',
    name: '72% Valrhona Molten Lava Cake',
    category: 'desserts',
    price: 16,
    desc: 'Warm single-origin Guanaja chocolate core paired with Madagascar bourbon vanilla bean gelato and 24k gold leaf.',
    image: 'https://images.unsplash.com/photo-1606313564200-e75d5e30476c?auto=format&fit=crop&w=700&q=80',
    rating: 5.0,
    reviews: 310,
    calories: 490,
    prepTime: '14 mins',
    tags: ['Vegetarian', "Chef's Choice"],
    macros: { protein: '9g', carbs: '54g', fats: '30g' },
    ingredients: ['Valrhona 72% Chocolate', 'Bourbon Vanilla Pods', 'Heavy Cream', 'Pasture Eggs', 'Raspberry Coulis'],
    allergens: ['Dairy', 'Eggs', 'Gluten'],
    isFeatured: true
  },
  {
    id: 'dish-8',
    name: 'Tahitian Vanilla Bean Crème Brûlée',
    category: 'desserts',
    price: 14,
    desc: 'Velvety baked custard under a hand-torched caramelized sugar crackle, garnished with organic valley blackberries.',
    image: 'https://images.unsplash.com/photo-1528975604071-b4dc52a2d18c?auto=format&fit=crop&w=700&q=80',
    rating: 4.8,
    reviews: 165,
    calories: 420,
    prepTime: '10 mins',
    tags: ['Vegetarian', 'Gluten-Free'],
    macros: { protein: '7g', carbs: '38g', fats: '26g' },
    ingredients: ['Tahitian Vanilla Beans', 'Organic Cream', 'Egg Yolks', 'Turbinado Sugar', 'Blackberries'],
    allergens: ['Dairy', 'Eggs'],
    isFeatured: false
  },
  {
    id: 'dish-9',
    name: 'Smoked Rosemary & Fig Elixir',
    category: 'beverages',
    price: 13,
    desc: 'Roasted black mission fig cordial, clarified crisp cider, Meyer lemon, tonic, and a smoking torched rosemary spear.',
    image: 'https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?auto=format&fit=crop&w=700&q=80',
    rating: 4.9,
    reviews: 77,
    calories: 110,
    prepTime: '5 mins',
    tags: ['Vegan', 'Gluten-Free', 'Organic'],
    macros: { protein: '1g', carbs: '26g', fats: '0g' },
    ingredients: ['Fig Cordial', 'Clarified Apple Cider', 'Smoked Rosemary', 'Meyer Lemon', 'Botanical Tonic'],
    allergens: [],
    isFeatured: false
  },
  {
    id: 'dish-10',
    name: 'Sicilian Blood Orange & Hibiscus Spritz',
    category: 'beverages',
    price: 12,
    desc: 'Fresh pressed Moro blood oranges, Egyptian wild hibiscus tea, elderflower syrup, and effervescent sparkling water.',
    image: 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?auto=format&fit=crop&w=700&q=80',
    rating: 4.7,
    reviews: 92,
    calories: 95,
    prepTime: '5 mins',
    tags: ['Vegan', 'Gluten-Free'],
    macros: { protein: '0g', carbs: '22g', fats: '0g' },
    ingredients: ['Blood Orange Juice', 'Hibiscus Petals', 'Elderflower Extract', 'Sparkling Soda', 'Fresh Mint'],
    allergens: [],
    isFeatured: false
  }
];

export const TESTIMONIALS = [
  { quote: 'Chef Silva turns every ingredient into a transcendent experience. The sea bass and filet mignon are culinary masterpieces.', author: 'Johnathan C.', outlet: 'The Epicurean Standard' },
  { quote: 'Fast, impeccably packaged delivery that arrives steaming hot. Savoria proves fine dining at home is genuinely achievable.', author: 'Dr. Evelyn Reed', outlet: 'Food & Wine Dispatch' },
  { quote: 'The best bistro in Colombo. Stunning flavors, mindful sourcing, and extraordinary hospitality.', author: 'Marcella Sterling', outlet: 'Connoisseur Dining' }
];
